# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSSweetSugar' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry'
  # Pods for iOSSweetSugar

  target 'iOSSweetSugarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSSweetSugarUITests' do
    # Pods for testing
  end

end
